version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: standup_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres/standup_manager
      - SECRET_KEY=dev_secret_key
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    environment:
      - API_URL=http://backend:8000
      - SECRET_KEY=dev_secret_key
    depends_on:
      - backend

volumes:
  postgres_data: